### ISSUE TITLE
What does this export?

### ISSUE THREAD

**Issue by jackmcdade** [Youfront/statamic-export#1]
It's not clear from the short README what exactly this is exporting. I bet a bit more explanation and documentation would go a long way towards people using it. I am more than happy to proofread and edit anything you write if that would help!

😊

**Comment by andershagbard** [comment]
I actually been wanting to make it more clear how do use this, as it is not the most visible action. It basically creates an action, which creates a CSV file, with all fields within the selected entries.

![image](https://user-images.githubusercontent.com/9662430/98789774-12921f00-2403-11eb-98b8-68d31f4256d2.png)

This has to do, until I get the docs updated 😅

**Comment by jackmcdade** [comment]
Neat!

**Comment by andershagbard** [comment]
Readme has been updated.
